services:
  kafka:
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka

#  sonarqube:
#    image: sonarqube:latest
#    container_name: sonarqube
#    ports:
#      - "9000:9000"
#    environment:
#      - SONAR_JDBC_URL=jdbc:postgresql://postgres:5432/sonar_db
#      - SONAR_JDBC_USERNAME=postgres
#      - SONAR_JDBC_PASSWORD=postgres
#    depends_on:
#      - postgres
#    networks:
#      - wanderly-network

  gateway-service:
    image: wanderly-gateway-service:latest
    container_name: gateway-service
    build:
      context: ./gateway-service
    depends_on:
      - discovery-service
      - config-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_URL: config-service
    ports:
      - "9191:9191"
    networks:
      - wanderly-network

  auth-service:
    image: wanderly-auth-service:latest
    container_name: auth-service
    build:
      context: ./auth-service
    depends_on:
      - postgres
      - redis
      - discovery-service
      - config-service
      - kafka
      - gateway-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_URL: config-service
    ports:
      - "8081:8081"
    networks:
      - wanderly-network

  notification-service:
    image: wanderly-notification-service:latest
    container_name: notification-service
    build:
      context: ./notification-service
    depends_on:
      - discovery-service
      - config-service
      - kafka
      - gateway-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_URL: config-service
    ports:
      - "8082:8082"
    networks:
      - wanderly-network

  user-service:
    image: wanderly-user-service:latest
    container_name: user-service
    build:
      context: ./user-service
    depends_on:
      - postgres
      - discovery-service
      - config-service
      - kafka
      - gateway-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_URL: config-service
    ports:
      - "8083:8083"
    networks:
      - wanderly-network

  geo-service:
    image: wanderly-geo-service:latest
    container_name: geo-service
    build:
      context: ./geo-service
    depends_on:
      - postgres
      - redis
      - discovery-service
      - config-service
      - kafka
      - gateway-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_URL: config-service
    ports:
      - "8084:8084"
    networks:
      - wanderly-network
