spring:
  application:
    name: geo-service


  config:
    import: 'optional:configserver:http://${CONFIG_URL:localhost}:8888'

  cloud:
    config:
      retry:
        max-attempts: 5
        initial-interval: 2000 # default multiplier: 1.1
        max-interval: 10000
      fail-fast: true
